language: node_js
node_js:
  - "6.3.0"
sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "npm run test"
addons:
  code_climate:
      repo_token: 45f0fcd76c25048c825d4f45f4d17f141358e1519a9c8ba54f792885499477e7
